# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Any commit that contains [build] will now trigger these jobs, everything else will be skipped.
    # if: "contains(github.event.head_commit.message, '[build]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Library
        shell: cmd
        run: call .\.github\workflows\build.bat

      #- name: Build Artifact
      #  shell: cmd
      #  run: 7z a -tzip ucxxrt.zip ucxxrt\

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ucxxrt
          path: ucxxrt\
          if-no-files-found: error
